{
 "title": "jetson_nano_debug_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource_Prom", "label": "datasource", "query": "prometheus" },
   { "name": "PromJobName", "label": "job_name", "query": "jetson,lijialun_pc" }
  ]
 },
 "panels": [
  { "title": "CPU MEM PCI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cpu_utilization{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCI List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg by(device) (pci_list_item{job=\"$PromJobName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "mem_utilization{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "NET DEV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Net device receive",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg by(net_dev) (receive{job=\"$PromJobName\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Net device transmit",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "avg by(net_dev) (transmit{job=\"$PromJobName\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "net dev info",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_dev{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SOUTHBRIDGE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Iostat wtrn kb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "iostat_kB_wrtn{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Iostat read kb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "iostat_kB_read{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Iostat read kb per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "iostat_kB_read_per_second{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Iostat wtrn kb per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "iostat_kB_wrtn_per_second{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Iostat dev info",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iostat_device{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "GPUUtilization{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Mem Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "GPUMemUtilization{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU MEM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "GPUMemTotal{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPUMemFree{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPUMemUsed{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU info",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "GPUID{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JETSON ONLY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Jetson nano CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "jetson_cpu_info{job=\"$PromJobName\", cpu_id=~\"cpu_0_val|cpu_1_val|cpu_2_val|cpu_3_val\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jetson nano CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "jetson_cpu_info{job=\"$PromJobName\", cpu_id=~\"cpu_0_frq|cpu_1_frq|cpu_2_frq|cpu_3_frq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jetson nano temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "jetson_temp_info{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jetson nano temperature",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "jetson_vals_info{job=\"$PromJobName\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}